<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'zf2rapid-library/widget/bootstrap-alert'       => __DIR__ . '/view/zf2rapid-library/widget/bootstrap-alert.phtml',
    'zf2rapid-library/widget/bootstrap-form-submit' => __DIR__ . '/view/zf2rapid-library/widget/bootstrap-form-submit.phtml',
    'zf2rapid-library/widget/bootstrap-form-group'  => __DIR__ . '/view/zf2rapid-library/widget/bootstrap-form-group.phtml',
);
