<?php
/**
 * ZF2rapid library
 *
 * @package    ZF2rapidLib
 * @link       https://github.com/ZFrapid/zf2rapid-library
 * @copyright  Copyright (c) 2014 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Bootstrap form group widget view script
 *
 * @package    ZF2rapidLib
 */
?>
<div class="form-group">
    <?php echo $this->formLabel($this->element); ?>
    <div class="col-sm-10">
        <?php echo $this->formElement($this->element); ?>
        <?php echo $this->formElementErrors($this->element); ?>
    </div>
</div>