<?php
/**
 * ZF2rapid library
 *
 * @package    ZF2rapidLib
 * @link       https://github.com/ZFrapid/zf2rapid-library
 * @copyright  Copyright (c) 2014 Ralf Eggert
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

/**
 * Bootstrap form submit widget view script
 *
 * @package    ZF2rapidLib
 */
?>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php foreach ($this->submitElements as $element): ?>
            <?php echo $this->formElement($element); ?>
        <?php endforeach; ?>
    </div>
</div>